name: taobaotools
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  qr_flutter: ^4.1.0
  qr_image_generator: ^0.2.8
  path_provider: ^2.1.1
  flukit: ^3.0.1
  download: ^1.0.0
  dio: ^5.3.3
  http: ^1.1.0
  fluent_ui: ^4.7.6
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
